### ISSUE TITLE
Add an empty template and a template for bot commands

### ISSUE THREAD

**Issue by isuruf** [conda-forge/.github#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

cc @BastianZim, @jaimergp 

see https://github.com/conda-forge/cypari2-feedstock/issues/38

### Installed packages

```shell
a
```

### Environment info

```shell
a
```

**Comment by jaimergp** [comment]
"A lot more work" as in one more click? There's a link after the selection box, "Open a blank issue":

![image](https://user-images.githubusercontent.com/2559438/156433881-90bd11b6-082c-44a4-a4ed-3c08085e09db.png)

**Comment by isuruf** [comment]
Ah, didn't see the blank issue link. Maybe it can be made to be more prominent?

**Comment by jaimergp** [comment]
That said, we can also add one entry labeled "Issue a bot command", where the template lists the available commands but requires no extra actions. Still one more click, but with increased user-friendliness at the same click cost?

**Comment by BastianZim** [comment]
GitHub templates doesn't allow us to fill in the title but I guess we can add some info about bot commands.

RE more prominent: This is done by Github and we cannot change the styling, we can only add a note to the issue text under "Bug report".

**Comment by BastianZim** [comment]
What I would suggest is that we create a conda-forge docs page about blank issues and possible commands and then we add it as a link in the selection page under the "Conda-forge documentation" button.

**Comment by jaimergp** [comment]
Thanks @BastianZim! Tag me in the PR whenever you feel it's ready for review or comments!

**Comment by isuruf** [comment]
> RE more prominent: This is done by Github and we cannot change the styling, we can only add a note to the issue text under "Bug report".

Can we make another template that is just blank?

**Comment by BastianZim** [comment]
Definitely. I'll add a generic one as well. 

It cannot be completely blank but something like "Your comment" shouldn't be too disrupting. Something like the one we added in staged-recipes: https://github.com/conda-forge/staged-recipes/blob/main/.github/ISSUE_TEMPLATE/issue_template.yml

**Comment by BastianZim** [comment]
Hi everybody, PR is in https://github.com/conda-forge/.github/pull/15
