### ISSUE TITLE
@conda-forge-admin, please add user @mwouts

### ISSUE THREAD

**Issue by asford** [conda-forge/.github#25]
### Additional comment

**Comment by asford** [comment]
Whoops, bug in issue template.

**Comment by isuruf** [comment]
Which issue template?

**Comment by asford** [comment]
I opened an issue in a feedstock (itables) via the issue template link in the GitHub ios app, which appeared to open the new issue template targeting this repo?

**Comment by isuruf** [comment]
That looks like an ios app bug. We've had two other open issues like this before. Would you be able to report this to github?

**Comment by asford** [comment]
Opened https://github.com/orgs/community/discussions/32087
