### ISSUE TITLE
are the workflow templates supposed to appear automatically?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/.github#4]
I guess these templates are for making new ones in a repo?

They did not appear in this repo I think

https://github.com/conda-forge/test-test

**Comment by beckermr** [comment]
Yeah, I am not seeing them when I set up the workflow by hand either.

**Comment by apidwalinsubport** [comment]
> I guess these templates are for making new ones in a repo?
> 
> They did not appear in this repo I think
> 
> https://github.com/conda-forge/test-test

**Comment by beckermr** [comment]
closing this as this doesn't seem to be planned
